os: linux
dist: bionic
language: scala
scala:
  - 2.11.12
jdk:
  - openjdk8
env:
  - UNIT_CONTROL_SOCKET_PATH=~/unit/unit-control.sock
before_install:
  - curl -sL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
  - echo "deb https://packages.nginx.org/unit/ubuntu/ bionic unit" | sudo tee -a /etc/apt/sources.list.d/unit.list
  - echo "deb-src https://packages.nginx.org/unit/ubuntu/ bionic unit" | sudo tee -a /etc/apt/sources.list.d/unit.list
  - sudo apt-get update
  - sudo apt-get install -y libuv1-dev unit-dev
script:
  - ./mill -j $(nproc) mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources
  - ./mill -j $(nproc) mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll buildSources
  - ./mill -j $(nproc) __.fix --check
  - ./mill -j $(nproc) __.compile
  - mkdir -p ~/unit
  - unitd --control unix:"$UNIT_CONTROL_SOCKET_PATH" --log ~/unit/unit.log --pid ~/unit/unit.pid --state ~/unit/state
  - ./mill -j $(nproc) integration.test
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/local
    - $HOME/.mill
    - $HOME/.sbt
